name: Node CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: dependency
        run: yarn
      # - name: Tsc
        # run: npm run tsc
      # - name: Lint
        # run: npm run lint
      - name: Test
        run: yarn jest
      - name: Build development
        run: npm run build
